/**
 * UI Manager - Handles all user interface interactions and updates
 * Manages modals, controls, and UI state synchronization
 */

export class UIManager {
    constructor(app) {
        this.app = app;
        this.modals = {};
        this.controls = {};
        this.isInitialized = false;
        
        // UI state
        this.state = {
            selectedDanceStyle: 'freestyle',
            danceIntensity: 5,
            autoGenerateDance: true,
            currentCameraPreset: 'front'
        };
    }
    
    /**
     * Initialize UI manager and set up event listeners
     */
    async initialize() {
        this.setupControls();
        this.setupModals();
        this.setupEventListeners();
        this.updateUI();
        
        this.isInitialized = true;
        console.log('🎛️ UI Manager initialized');
    }
    
    /**
     * Set up control references
     */
    setupControls() {
        // Audio controls
        this.controls.loadAudio = document.getElementById('loadAudio');
        this.controls.audioUpload = document.getElementById('audioUpload');
        this.controls.recordVoice = document.getElementById('recordVoice');
        this.controls.volumeControl = document.getElementById('volumeControl');
        this.controls.audioInfo = document.getElementById('audioInfo');
        
        // Avatar controls
        this.controls.customizeAvatar = document.getElementById('customizeAvatar');
        this.controls.loadAvatar = document.getElementById('loadAvatar');
        this.controls.saveAvatar = document.getElementById('saveAvatar');
        
        // Dance controls
        this.controls.danceStyle = document.getElementById('danceStyle');
        this.controls.generateChoreography = document.getElementById('generateChoreography');
        this.controls.danceIntensity = document.getElementById('danceIntensity');
        
        // Background controls
        this.controls.loadBackground = document.getElementById('loadBackground');
        this.controls.backgroundUpload = document.getElementById('backgroundUpload');
        this.controls.presetBackground = document.getElementById('presetBackground');
        this.controls.animatedBackground = document.getElementById('animatedBackground');
        
        // Effects controls
        this.controls.addText = document.getElementById('addText');
        this.controls.addStickers = document.getElementById('addStickers');
        this.controls.particles = document.getElementById('particles');
        this.controls.lighting = document.getElementById('lighting');
        
        // Playback controls
        this.controls.playBtn = document.getElementById('playBtn');
        this.controls.pauseBtn = document.getElementById('pauseBtn');
        this.controls.stopBtn = document.getElementById('stopBtn');
        this.controls.timeDisplay = document.getElementById('timeDisplay');
        
        // Timeline controls
        this.controls.timelineSeeker = document.getElementById('timelineSeeker');
        this.controls.addKeyframe = document.getElementById('addKeyframe');
        this.controls.deleteKeyframe = document.getElementById('deleteKeyframe');
        
        // Camera controls
        this.controls.cameraZoom = document.getElementById('cameraZoom');
        this.controls.cameraRotation = document.getElementById('cameraRotation');
        
        // Main navigation
        this.controls.newProject = document.getElementById('newProject');
        this.controls.loadProject = document.getElementById('loadProject');
        this.controls.saveProject = document.getElementById('saveProject');
        this.controls.exportVideo = document.getElementById('exportVideo');
        
        // Performance monitor
        this.controls.fpsCounter = document.getElementById('fpsCounter');
        this.controls.memoryUsage = document.getElementById('memoryUsage');
        this.controls.webglStatus = document.getElementById('webglStatus');
        this.controls.canvasInfo = document.getElementById('canvasInfo');
    }
    
    /**
     * Set up modal references
     */
    setupModals() {
        this.modals.avatarCustomization = {
            element: document.getElementById('avatarCustomizationModal'),
            body: document.getElementById('avatarCustomizationModal').querySelector('.modal-body')
        };
        
        this.modals.textEditor = {
            element: document.getElementById('textEditorModal'),
            body: document.getElementById('textEditorModal').querySelector('.modal-body')
        };
        
        this.modals.export = {
            element: document.getElementById('exportModal'),
            body: document.getElementById('exportModal').querySelector('.modal-body')
        };
        
        // Set up close buttons
        Object.values(this.modals).forEach(modal => {
            const closeBtn = modal.element.querySelector('.close-modal');
            if (closeBtn) {
                closeBtn.addEventListener('click', () => {
                    this.hideModal(modal.element);
                });
            }
            
            // Close on backdrop click
            modal.element.addEventListener('click', (e) => {
                if (e.target === modal.element) {
                    this.hideModal(modal.element);
                }
            });
        });
    }
    
    /**
     * Set up event listeners for all UI controls
     */
    setupEventListeners() {
        // Audio controls
        this.controls.loadAudio?.addEventListener('click', () => {
            this.controls.audioUpload.click();
        });
        
        this.controls.audioUpload?.addEventListener('change', (e) => {
            if (e.target.files[0]) {
                this.app.loadAudio(e.target.files[0]);
            }
        });
        
        this.controls.volumeControl?.addEventListener('input', (e) => {
            this.app.audio?.setVolume(e.target.value / 100);
        });
        
        // Avatar controls
        this.controls.customizeAvatar?.addEventListener('click', () => {
            this.showAvatarCustomizationModal();
        });
        
        // Dance controls
        this.controls.danceStyle?.addEventListener('change', (e) => {
            this.state.selectedDanceStyle = e.target.value;
        });
        
        this.controls.generateChoreography?.addEventListener('click', () => {
            this.app.generateDance();
        });
        
        this.controls.danceIntensity?.addEventListener('input', (e) => {
            this.state.danceIntensity = parseInt(e.target.value);
        });
        
        // Background controls
        this.controls.loadBackground?.addEventListener('click', () => {
            this.controls.backgroundUpload.click();
        });
        
        this.controls.backgroundUpload?.addEventListener('change', (e) => {
            if (e.target.files[0]) {
                this.loadBackground(e.target.files[0]);
            }
        });
        
        this.controls.presetBackground?.addEventListener('change', (e) => {
            this.loadPresetBackground(e.target.value);
        });
        
        // Effects controls
        this.controls.addText?.addEventListener('click', () => {
            this.showTextEditorModal();
        });
        
        // Playback controls
        this.controls.playBtn?.addEventListener('click', () => {
            this.app.play();
        });
        
        this.controls.pauseBtn?.addEventListener('click', () => {
            this.app.pause();
        });
        
        this.controls.stopBtn?.addEventListener('click', () => {
            this.app.stop();
        });
        
        // Timeline controls
        this.controls.timelineSeeker?.addEventListener('input', (e) => {
            const progress = e.target.value / 100;
            const time = progress * this.app.totalDuration;
            this.app.seek(time);
        });
        
        // Camera controls
        this.controls.cameraZoom?.addEventListener('input', (e) => {
            this.app.scene?.setCameraZoom(parseFloat(e.target.value));
        });
        
        this.controls.cameraRotation?.addEventListener('input', (e) => {
            this.app.scene?.setCameraRotation(parseFloat(e.target.value));
        });
        
        // Camera presets
        document.querySelectorAll('.preset-btn').forEach(btn => {
            btn.addEventListener('click', (e) => {
                const preset = e.target.dataset.preset;
                this.setCameraPreset(preset);
            });
        });
        
        // Main navigation
        this.controls.newProject?.addEventListener('click', () => {
            this.app.newProject();
        });
        
        this.controls.loadProject?.addEventListener('click', () => {
            this.app.loadProject();
        });
        
        this.controls.saveProject?.addEventListener('click', () => {
            this.app.saveProject();
        });
        
        this.controls.exportVideo?.addEventListener('click', () => {
            this.showExportModal();
        });
    }
    
    /**
     * Update UI state
     */
    update(deltaTime) {
        if (!this.isInitialized) return;
        
        // Update time display
        this.updateTimeDisplay();
        
        // Update timeline seeker
        if (this.app.totalDuration > 0) {
            const progress = (this.app.currentTime / this.app.totalDuration) * 100;
            if (this.controls.timelineSeeker) {
                this.controls.timelineSeeker.value = progress;
            }
        }
    }
    
    /**
     * Update time display
     */
    updateTimeDisplay() {
        if (!this.controls.timeDisplay) return;
        
        const current = this.formatTime(this.app.currentTime);
        const total = this.formatTime(this.app.totalDuration);
        this.controls.timeDisplay.textContent = `${current} / ${total}`;
    }
    
    /**
     * Update playback controls state
     */
    updatePlaybackControls() {
        if (this.controls.playBtn) {
            this.controls.playBtn.style.opacity = this.app.isPlaying ? '0.5' : '1';
        }
        if (this.controls.pauseBtn) {
            this.controls.pauseBtn.style.opacity = this.app.isPlaying ? '1' : '0.5';
        }
    }
    
    /**
     * Update title with dirty state
     */
    updateTitle() {
        const title = 'Anime Dance Animation Generator';
        document.title = this.app.state.isDirty ? `${title} *` : title;
    }
    
    /**
     * Update performance monitor
     */
    updatePerformanceMonitor(fps, memory) {
        if (this.controls.fpsCounter) {
            this.controls.fpsCounter.textContent = Math.round(fps);
        }
        if (this.controls.memoryUsage) {
            this.controls.memoryUsage.textContent = `${Math.round(memory)} MB`;
        }
    }
    
    /**
     * Modal management
     */
    showModal(modal) {
        modal.classList.add('active');
        document.body.style.overflow = 'hidden';
    }
    
    hideModal(modal) {
        modal.classList.remove('active');
        document.body.style.overflow = '';
    }
    
    /**
     * Show avatar customization modal
     */
    showAvatarCustomizationModal() {
        const modal = this.modals.avatarCustomization;
        
        // Create avatar customization interface
        modal.body.innerHTML = `
            <div class="avatar-customization">
                <div class="avatar-preview">
                    <canvas id="avatarPreviewCanvas" width="300" height="400"></canvas>
                </div>
                <div class="avatar-controls">
                    <div class="control-group">
                        <h4>Face</h4>
                        <div class="control-row">
                            <label>Face Shape:</label>
                            <input type="range" id="faceShape" min="0" max="10" value="5">
                            <span class="value-display">5</span>
                        </div>
                        <div class="control-row">
                            <label>Eye Size:</label>
                            <input type="range" id="eyeSize" min="0" max="10" value="5">
                            <span class="value-display">5</span>
                        </div>
                        <div class="control-row">
                            <label>Eye Color:</label>
                            <div class="color-picker-group">
                                <div class="color-option active" style="background: #8B4513" data-color="#8B4513"></div>
                                <div class="color-option" style="background: #4169E1" data-color="#4169E1"></div>
                                <div class="color-option" style="background: #228B22" data-color="#228B22"></div>
                                <div class="color-option" style="background: #800080" data-color="#800080"></div>
                            </div>
                        </div>
                    </div>
                    <div class="control-group">
                        <h4>Hair</h4>
                        <div class="control-row">
                            <label>Hair Style:</label>
                            <select id="hairStyle">
                                <option value="short">Short</option>
                                <option value="medium">Medium</option>
                                <option value="long">Long</option>
                                <option value="ponytail">Ponytail</option>
                                <option value="twintails">Twin Tails</option>
                            </select>
                        </div>
                        <div class="control-row">
                            <label>Hair Color:</label>
                            <div class="color-picker-group">
                                <div class="color-option active" style="background: #8B4513" data-color="#8B4513"></div>
                                <div class="color-option" style="background: #FFD700" data-color="#FFD700"></div>
                                <div class="color-option" style="background: #000000" data-color="#000000"></div>
                                <div class="color-option" style="background: #FF69B4" data-color="#FF69B4"></div>
                                <div class="color-option" style="background: #9370DB" data-color="#9370DB"></div>
                            </div>
                        </div>
                    </div>
                    <div class="control-group">
                        <h4>Body</h4>
                        <div class="control-row">
                            <label>Height:</label>
                            <input type="range" id="bodyHeight" min="0" max="10" value="5">
                            <span class="value-display">5</span>
                        </div>
                        <div class="control-row">
                            <label>Build:</label>
                            <input type="range" id="bodyBuild" min="0" max="10" value="5">
                            <span class="value-display">5</span>
                        </div>
                    </div>
                    <div class="control-group">
                        <h4>Outfit</h4>
                        <div class="control-row">
                            <label>Style:</label>
                            <select id="outfitStyle">
                                <option value="casual">Casual</option>
                                <option value="school">School Uniform</option>
                                <option value="idol">Idol Outfit</option>
                                <option value="dance">Dance Costume</option>
                                <option value="fantasy">Fantasy</option>
                            </select>
                        </div>
                        <div class="control-row">
                            <label>Main Color:</label>
                            <div class="color-picker-group">
                                <div class="color-option active" style="background: #FF6B9D" data-color="#FF6B9D"></div>
                                <div class="color-option" style="background: #4ECDC4" data-color="#4ECDC4"></div>
                                <div class="color-option" style="background: #45B7D1" data-color="#45B7D1"></div>
                                <div class="color-option" style="background: #96CEB4" data-color="#96CEB4"></div>
                                <div class="color-option" style="background: #FECA57" data-color="#FECA57"></div>
                            </div>
                        </div>
                    </div>
                    <div class="control-group">
                        <h4>Presets</h4>
                        <div class="preset-avatars">
                            <div class="preset-avatar active" data-preset="default">Default</div>
                            <div class="preset-avatar" data-preset="cute">Cute</div>
                            <div class="preset-avatar" data-preset="cool">Cool</div>
                            <div class="preset-avatar" data-preset="elegant">Elegant</div>
                        </div>
                    </div>
                </div>
            </div>
        `;
        
        this.setupAvatarCustomizationEvents();
        this.showModal(modal.element);
    }
    
    /**
     * Show text editor modal
     */
    showTextEditorModal() {
        const modal = this.modals.textEditor;
        
        modal.body.innerHTML = `
            <div class="text-editor">
                <div class="text-preview">
                    <canvas id="textPreviewCanvas" width="500" height="400"></canvas>
                </div>
                <div class="text-properties">
                    <div class="text-input-group">
                        <h4>Text Content</h4>
                        <textarea id="textInput" class="text-input" placeholder="Enter your text here..."></textarea>
                    </div>
                    <div class="control-group">
                        <h4>Font</h4>
                        <div class="font-selector">
                            <div class="font-option active" data-font="Arial">Arial</div>
                            <div class="font-option" data-font="Impact">Impact</div>
                            <div class="font-option" data-font="Comic Sans MS">Comic Sans</div>
                            <div class="font-option" data-font="Times New Roman">Times</div>
                        </div>
                        <div class="control-row">
                            <label>Size:</label>
                            <input type="range" id="fontSize" min="12" max="120" value="48">
                            <span class="value-display">48</span>
                        </div>
                    </div>
                    <div class="control-group">
                        <h4>Animation</h4>
                        <div class="animation-path-selector">
                            <div class="path-option active" data-path="none">Static</div>
                            <div class="path-option" data-path="slide">Slide</div>
                            <div class="path-option" data-path="bounce">Bounce</div>
                            <div class="path-option" data-path="wave">Wave</div>
                            <div class="path-option" data-path="spiral">Spiral</div>
                        </div>
                        <div class="control-row">
                            <label>Speed:</label>
                            <input type="range" id="animationSpeed" min="0.1" max="5" step="0.1" value="1">
                            <span class="value-display">1</span>
                        </div>
                    </div>
                </div>
            </div>
        `;
        
        this.setupTextEditorEvents();
        this.showModal(modal.element);
    }
    
    /**
     * Show export modal
     */
    showExportModal() {
        const modal = this.modals.export;
        
        modal.body.innerHTML = `
            <div class="export-options">
                <div class="export-format">
                    <h4>Format</h4>
                    <div class="format-selector">
                        <div class="format-option active" data-format="mp4">
                            <div class="format-name">MP4</div>
                            <div class="format-description">Best compatibility</div>
                        </div>
                        <div class="format-option" data-format="webm">
                            <div class="format-name">WebM</div>
                            <div class="format-description">Smaller file size</div>
                        </div>
                        <div class="format-option" data-format="gif">
                            <div class="format-name">GIF</div>
                            <div class="format-description">Social media ready</div>
                        </div>
                    </div>
                </div>
                <div class="export-format">
                    <h4>Quality Settings</h4>
                    <div class="quality-settings">
                        <div class="quality-group">
                            <label>Resolution:</label>
                            <select id="exportResolution">
                                <option value="720p">720p (1280x720)</option>
                                <option value="1080p" selected>1080p (1920x1080)</option>
                                <option value="4k">4K (3840x2160)</option>
                            </select>
                        </div>
                        <div class="quality-group">
                            <label>Frame Rate:</label>
                            <select id="exportFrameRate">
                                <option value="24">24 FPS</option>
                                <option value="30" selected>30 FPS</option>
                                <option value="60">60 FPS</option>
                            </select>
                        </div>
                        <div class="quality-group">
                            <label>Bitrate:</label>
                            <select id="exportBitrate">
                                <option value="low">Low (2 Mbps)</option>
                                <option value="medium" selected>Medium (5 Mbps)</option>
                                <option value="high">High (10 Mbps)</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="export-actions">
                    <button id="startExport" class="btn-primary">Start Export</button>
                    <button id="cancelExport" class="btn-secondary">Cancel</button>
                </div>
            </div>
        `;
        
        this.setupExportEvents();
        this.showModal(modal.element);
    }
    
    /**
     * Set up avatar customization events
     */
    setupAvatarCustomizationEvents() {
        // Range inputs
        const ranges = ['faceShape', 'eyeSize', 'bodyHeight', 'bodyBuild'];
        ranges.forEach(id => {
            const input = document.getElementById(id);
            const display = input?.nextElementSibling;
            if (input && display) {
                input.addEventListener('input', (e) => {
                    display.textContent = e.target.value;
                    this.updateAvatarPreview();
                });
            }
        });
        
        // Color pickers
        document.querySelectorAll('.color-option').forEach(option => {
            option.addEventListener('click', (e) => {
                const group = e.target.parentElement;
                group.querySelectorAll('.color-option').forEach(opt => opt.classList.remove('active'));
                e.target.classList.add('active');
                this.updateAvatarPreview();
            });
        });
        
        // Presets
        document.querySelectorAll('.preset-avatar').forEach(preset => {
            preset.addEventListener('click', (e) => {
                document.querySelectorAll('.preset-avatar').forEach(p => p.classList.remove('active'));
                e.target.classList.add('active');
                this.loadAvatarPreset(e.target.dataset.preset);
            });
        });
    }
    
    /**
     * Set up text editor events
     */
    setupTextEditorEvents() {
        // Text input
        const textInput = document.getElementById('textInput');
        textInput?.addEventListener('input', () => {
            this.updateTextPreview();
        });
        
        // Font options
        document.querySelectorAll('.font-option').forEach(option => {
            option.addEventListener('click', (e) => {
                document.querySelectorAll('.font-option').forEach(opt => opt.classList.remove('active'));
                e.target.classList.add('active');
                this.updateTextPreview();
            });
        });
        
        // Animation paths
        document.querySelectorAll('.path-option').forEach(option => {
            option.addEventListener('click', (e) => {
                document.querySelectorAll('.path-option').forEach(opt => opt.classList.remove('active'));
                e.target.classList.add('active');
                this.updateTextPreview();
            });
        });
        
        // Font size
        const fontSize = document.getElementById('fontSize');
        const sizeDisplay = fontSize?.nextElementSibling;
        if (fontSize && sizeDisplay) {
            fontSize.addEventListener('input', (e) => {
                sizeDisplay.textContent = e.target.value;
                this.updateTextPreview();
            });
        }
    }
    
    /**
     * Set up export events
     */
    setupExportEvents() {
        // Format selection
        document.querySelectorAll('.format-option').forEach(option => {
            option.addEventListener('click', (e) => {
                document.querySelectorAll('.format-option').forEach(opt => opt.classList.remove('active'));
                e.target.classList.add('active');
            });
        });
        
        // Export button
        document.getElementById('startExport')?.addEventListener('click', () => {
            this.startExport();
        });
        
        // Cancel button
        document.getElementById('cancelExport')?.addEventListener('click', () => {
            this.hideModal(this.modals.export.element);
        });
    }
    
    /**
     * Helper methods
     */
    formatTime(seconds) {
        const mins = Math.floor(seconds / 60);
        const secs = Math.floor(seconds % 60);
        return `${mins.toString().padStart(2, '0')}:${secs.toString().padStart(2, '0')}`;
    }
    
    getSelectedDanceStyle() {
        return this.state.selectedDanceStyle;
    }
    
    getDanceIntensity() {
        return this.state.danceIntensity;
    }
    
    getAutoGenerateDance() {
        return this.state.autoGenerateDance;
    }
    
    setCameraPreset(preset) {
        this.state.currentCameraPreset = preset;
        document.querySelectorAll('.preset-btn').forEach(btn => {
            btn.classList.toggle('active', btn.dataset.preset === preset);
        });
        this.app.scene?.setCameraPreset(preset);
    }
    
    updateAvatarPreview() {
        // This would update the avatar preview canvas
        console.log('Updating avatar preview...');
    }
    
    updateTextPreview() {
        // This would update the text preview canvas
        console.log('Updating text preview...');
    }
    
    loadAvatarPreset(preset) {
        // This would load a predefined avatar configuration
        console.log(`Loading avatar preset: ${preset}`);
    }
    
    loadBackground(file) {
        console.log(`Loading background: ${file.name}`);
        this.app.scene?.loadBackground(file);
    }
    
    loadPresetBackground(preset) {
        console.log(`Loading preset background: ${preset}`);
        this.app.scene?.loadPresetBackground(preset);
    }
    
    startExport() {
        const format = document.querySelector('.format-option.active')?.dataset.format || 'mp4';
        const resolution = document.getElementById('exportResolution')?.value || '1080p';
        const frameRate = document.getElementById('exportFrameRate')?.value || '30';
        const bitrate = document.getElementById('exportBitrate')?.value || 'medium';
        
        this.hideModal(this.modals.export.element);
        
        this.app.exportVideo({
            format,
            resolution,
            fps: parseInt(frameRate),
            quality: bitrate
        });
    }
    
    showExportProgress() {
        // Show export progress UI
        console.log('Showing export progress...');
    }
    
    updateExportProgress(progress) {
        // Update export progress
        console.log(`Export progress: ${progress}%`);
    }
    
    hideExportProgress() {
        // Hide export progress UI
        console.log('Hiding export progress...');
    }
    
    showConfirmDialog(title, message) {
        return new Promise((resolve) => {
            const result = confirm(`${title}\n\n${message}`);
            resolve(result);
        });
    }
    
    updateUI() {
        this.updateTimeDisplay();
        this.updatePlaybackControls();
        this.updateTitle();
    }
}